window.env = {
  REACT_APP_TITLE: "$APP_TITLE",
  REACT_APP_DESCRIPTION_CONTENT: "$DESCRIPTION",
  REACT_APP_API_BASE_URL: "http://api.cmcati.vn",
  REACT_APP_FRONT_URL: "$FRONT_URL",
  REACT_APP_CLIENT_ID: "web-app",
  REACT_APP_SUPERSET_URL:"$SUPERSET_URL",
  REACT_APP_CLIENT_SECRET: "bb2b9088-fedc-4f1d-b5ca-96bcf68ebd3a",
  REACT_APP_CALENDAR_TYPE : "$CALENDAR_TYPE",
};
